"""Apply-marker: per-model mtime tracking in .cache/last_apply.json.

The marker records the mtime (as a float timestamp) of each model's
graph.pbtxt at the time apply last ran successfully. On the next apply,
if the current mtime is newer, we warn that the file may have been
regenerated by ovms --pull and patches are being re-applied.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_CACHE_DIR = Path(".cache")
_MARKER_FILE = _CACHE_DIR / "last_apply.json"


def load() -> dict[str, float]:
    """Return the stored mtime map, or empty dict if not present."""
    if not _MARKER_FILE.exists():
        return {}
    try:
        return json.loads(_MARKER_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def warn_if_stale(model_name: str, pbtxt_path: Path, marker: dict[str, float]) -> None:
    """Emit a warning if pbtxt is newer than the last-apply timestamp."""
    if not pbtxt_path.exists():
        return
    last = marker.get(model_name)
    if last is None:
        return
    current_mtime = pbtxt_path.stat().st_mtime
    if current_mtime > last:
        logger.warning(
            "[apply] %s: pbtxt may have been regenerated after last apply "
            "(mtime %.3f > marker %.3f), re-applying patches now",
            model_name, current_mtime, last,
        )


def update(model_name: str, pbtxt_path: Path, marker: dict[str, float]) -> None:
    """Record the current mtime of pbtxt_path into marker (in-place)."""
    if pbtxt_path.exists():
        marker[model_name] = pbtxt_path.stat().st_mtime


def save(marker: dict[str, float]) -> None:
    """Persist the marker to disk. Creates .cache/ if necessary."""
    _CACHE_DIR.mkdir(exist_ok=True)
    _MARKER_FILE.write_text(json.dumps(marker, indent=2), encoding="utf-8")
